chore(deps): disable mkl as it is broken at the moment
zama-ai/concrete-fftw pull request #15
Opened 2022-07-12 09:09 UTC by IceTDrinker

For now remove the mkl feature and update the CI file.

intel mkl crate seems to be left to its own fate and currently does not compile, we remove it for the time being before a more permanent solution.

2022-07-12 11:27 UTC, aPere3 requested changes
Thank you for removing that ! 

Unfortunately, I believe that you missed some changes to be done in some files. Grepping the repo for `mkl` at least returns:
```shell
./concrete-fftw-sys/build.rs:    if cfg!(macos) && cfg!(feature = "mkl") {
./concrete-fftw-sys/build.rs:        panic!("Mkl is not supported in the macos platform.")
./concrete-fftw-sys/src/lib.rs:#[cfg(not(feature = "mkl"))]
./concrete-fftw-sys/src/lib.rs:#[cfg(not(feature = "mkl"))]
./concrete-fftw-sys/src/lib.rs:#[cfg(feature = "mkl")]
./concrete-fftw-sys/src/lib.rs:extern crate intel_mkl_src as ffi;
```

Good luck ! :smiley:

2022-07-12 11:56 UTC, IceTDrinker commented
> Okay for that, good idea ! But we must really make sure that we take a decision on this topic in a near future then !

Agreed, issue for it is #14

2022-07-12 14:17 UTC, IceTDrinker commented
As discussed, mkl has been removed in the end.

2022-07-13 07:30 UTC, aPere3 requested changes

2022-07-13 07:44 UTC, IceTDrinker commented on concrete-fftw/LICENSE.txt
> -    SOFTWARE.
Ah yes, my bad 🤦‍♂️

2022-07-13 08:06 UTC, IceTDrinker commented
Done !

2022-07-13 08:07 UTC, aPere3 approved these changes

2022-07-13 08:23 UTC, merged